-- Add missing columns to users table
ALTER TABLE users
ADD COLUMN IF NOT EXISTS full_name VARCHAR(100) NOT NULL DEFAULT '' AFTER username,
ADD COLUMN IF NOT EXISTS last_login TIMESTAMP NULL DEFAULT NULL;

-- Add missing columns to networks table
ALTER TABLE networks
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Add missing columns to services table
ALTER TABLE services
ADD COLUMN IF NOT EXISTS description TEXT NULL,
ADD COLUMN IF NOT EXISTS price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Add missing columns to invoices table
ALTER TABLE invoices
ADD COLUMN IF NOT EXISTS number VARCHAR(50) NOT NULL DEFAULT '' AFTER id,
ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Add missing columns to payments table
ALTER TABLE payments
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
